// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAID_88N1e_V-_xzdQFv2hMgZvLHHHDXYU',
    appId: '1:441308839671:web:36940b56fba51f8bc1ddf2',
    messagingSenderId: '441308839671',
    projectId: 'taeapp08',
    authDomain: 'taeapp08.firebaseapp.com',
    storageBucket: 'taeapp08.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_xYt1BXlbzMZ0-QRry0xM3eVtFf0XrdU',
    appId: '1:441308839671:android:3d9dd05b0a921070c1ddf2',
    messagingSenderId: '441308839671',
    projectId: 'taeapp08',
    storageBucket: 'taeapp08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN5A3J6mwJUTUbEsoUVKXl2_hpYoLKdeo',
    appId: '1:441308839671:ios:a0bb12a2c8b0b983c1ddf2',
    messagingSenderId: '441308839671',
    projectId: 'taeapp08',
    storageBucket: 'taeapp08.firebasestorage.app',
    iosBundleId: 'com.example.taeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN5A3J6mwJUTUbEsoUVKXl2_hpYoLKdeo',
    appId: '1:441308839671:ios:a0bb12a2c8b0b983c1ddf2',
    messagingSenderId: '441308839671',
    projectId: 'taeapp08',
    storageBucket: 'taeapp08.firebasestorage.app',
    iosBundleId: 'com.example.taeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAID_88N1e_V-_xzdQFv2hMgZvLHHHDXYU',
    appId: '1:441308839671:web:aec24993d2b3c338c1ddf2',
    messagingSenderId: '441308839671',
    projectId: 'taeapp08',
    authDomain: 'taeapp08.firebaseapp.com',
    storageBucket: 'taeapp08.firebasestorage.app',
  );

}